name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Current branch
      uses: actions/checkout@v1
    - name: Build Docker Image
      run: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && ./build.sh
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}